name: "Building"
description: "Compiles the project"

runs:
  using: "composite"
  steps:
    - name: Install Conan
      shell: bash
      run: pip install conan

    - name: Configure Conan
      shell: bash
      run: conan profile detect --force

    - name: Install dependencies
      shell: bash
      run: conan install . --output-folder=. --build=missing

    - name: Configure CMake
      shell: bash
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake

    - name: Build
      shell: bash
      run: cmake --build build

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libmicrohttpd-dev libcjson-dev

    - name: Clone prometheus client
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c
        rm -rf promhttp

    - name: Buillding and Installing prometheus
      shell: bash
      run: |
        cd prometheus-client-c/prom
        mkdir -p build 
        cd build
        cmake ..
        make
        sudo make install
    - name: Building th main proyect
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
        sudo make install