name: "Building"
description: "Compiles the project"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libmicrohttpd-dev libcjson-dev python3-pip

    - name: Install Conan
      shell: bash
      run: pip install --user conan

    - name: Configure Conan
      shell: bash
      run: conan profile detect --force

    - name: Install dependencies
      shell: bash
      run: conan install . --output-folder=build --build=missing

    - name: Clone prometheus client
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c
        rm -rf promhttp

    - name: Build and Install prometheus client
      shell: bash
      run: |
        cd prometheus-client-c/prom
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        sudo make install

    - name: Configure main project with CMake
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -S .. \
              -B . \
              -DCMAKE_TOOLCHAIN_FILE=../build/generators/conan_toolchain.cmake \
              -DCMAKE_BUILD_TYPE=Release

    - name: Build main project
      shell: bash
      run: |
        cd build
        cmake --build . -- -j$(nproc)
