name: "Building"
description: "Compiles the project"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get install -y cmake build-essential git libmicrohttpd-dev python3-pip

    - name: Clone prometheus-client-c
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git

    - name: Patch promhttp_handler return type
      shell: bash
      run: |
        sed -i 's/^int[[:space:]]\+promhttp_handler(/enum MHD_Result promhttp_handler(/' prometheus-client-c/promhttp/src/promhttp.c

    - name: Install Conan
      shell: bash
      run: |
        pip3 install conan

    - name: Setup Conan profile
      shell: bash
      run: |
        conan profile detect --force

    - name: Install dependencies with Conan
      shell: bash
      run: |
        conan install . --output-folder=. --build=missing

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      shell: bash
      run: |
        cmake --build build
