name: "Building"
description: "Compiles the project"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential git libmicrohttpd-dev libcjson-dev python3-pip

    - name: Clone prometheus client
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c
        rm -rf promhttp

    - name: Building and Installing Prometheus
      shell: bash
      run: |
        cd prometheus-client-c/prom
        mkdir -p build
        cd build
        cmake ..
        make 
        sudo make install

    - name: Build main project
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake ..
        make 