name : MainAction

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with:
          submodules: recursive
        
      - name: Install QA dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest 
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format valgrind bc
          version: 1.0

      - name: Documentation 
        uses: ./.github/actions/documentation

      #- name: Coverage
      #  uses: ./.github/actions/coverage

      - name: Style
        uses: ./.github/actions/style-facu    

      - name: Building
        uses: ./.github/actions/building
        
      